spring.application.name=feign-client-demo

server.port=8085

spring.cloud.inetutils.preferred-networks=127.0.0.1
spring.cloud.inetutils.ignored-interfaces=VMware.*,VirtualBox.*,Hyper-V.*

spring.cloud.client.hostname=localhost
