spring.application.name=book-service

spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.initialization-fail-timeout=60000

spring.sql.init.continue-on-error=true
spring.sql.init.mode=always


server.port=5000

# ===============================
# DataSource Configuration
# ===============================
spring.datasource.url=jdbc:oracle:thin:@oracledb:1521/t3
spring.datasource.username=system
spring.datasource.password=password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update