spring.application.name=food-api

server.port=5000

# ===============================
# DataSource Configuration
# ===============================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=sys as sysdba
spring.datasource.password=password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update